name: Rust Servers Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: latest

      - name: Add MSVC tools to PATH
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      #  如果需要构建 native libraries，请在此处添加步骤

      - name: Build Rust project
        run: cargo build --release

      - name: Run servers (选择以下一种方案)

        # 方案一：顺序执行
      - name: Run sakura-sdk-server
        run: cargo run --release --bin sakura-sdk-server
      - name: Run sakura-dispatch-server
        run: cargo run --release --bin sakura-dispatch-server
      - name: Run sakura-gate-server
        run: cargo run --release --bin sakura-gate-server
      - name: Run sakura-game-server
        run: cargo run --release --bin sakura-game-server
