name: Build and Release

on:
  push:
    branches: [ main ] # 或者你的主分支名称
  release:
    types: [ created ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rust Marker Linter
        uses: rust-marker/marker@v0.4.3
        with: 
          

      - name: Build sakura-sdk-server
        run: cargo build --release --bin sakura-sdk-server

      - name: Build sakura-dispatch-server
        run: cargo build --release --bin sakura-dispatch-server

      - name: Build sakura-gate-server
        run: cargo build --release --bin sakura-gate-server

      - name: Build sakura-game-server
        run: cargo build --release --bin sakura-game-server

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server-binaries
          path: target/release

      # 可选：发布到 GitHub Releases
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
