name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo run --release --bin sakura-sdk-server
cargo run --release --bin sakura-dispatch-server
cargo run --release --bin sakura-gate-server
cargo run --release --bin sakura-game-server
    - name: Run tests
      run: cargo test --verbose
